import { createHash } from "node:crypto";
import { fail } from "./errors.mjs";

export const isCompaction = (item) =>
  ["compaction", "compaction_summary", "context_compaction"].includes(
    item.type,
  );
const digest = (value) => createHash("sha256").update(value).digest("hex");
const key = (ctx, item) => {
  if (typeof item.encrypted_content !== "string" || !item.encrypted_content)
    throw fail("invalid_compaction_item", 400);
  return "checkpoint:" + ctx.owner + ":" + digest(item.encrypted_content);
};

// Item ids and Codex-only message metadata can change when the client rebuilds history.
const fingerprint = (item) => {
  if (item.type === "message" || item.role) {
    const content =
      typeof item.content === "string"
        ? item.content
        : (item.content ?? []).map((x) => x.text ?? JSON.stringify(x)).join("");
    return digest(JSON.stringify([item.role, content]));
  }
  return digest(JSON.stringify(item));
};

export function saveCheckpoint(state, ctx, item, checkpoint) {
  state.set(key(ctx, item), checkpoint, ctx);
}

export function expandCheckpoints(
  state,
  ctx,
  input,
  target,
  { portable = false } = {},
) {
  let expanded = [],
    count = 0,
    source;
  for (const item of input) {
    if (!isCompaction(item)) {
      expanded.push(item);
      continue;
    }
    const checkpoint = state.get(key(ctx, item));
    // Official encrypted state is validated by the authenticated official backend.
    // Local cache loss must not block native continuation. Never send our virtual
    // checkpoint handles to that backend or opaque official state to another provider.
    if (!checkpoint && !portable && target.provider === "chatgpt-subscription" &&
        typeof item.encrypted_content === "string" &&
        !item.encrypted_content.startsWith("gateway-checkpoint-")) {
      expanded.push(item);
      continue;
    }
    const original = checkpoint?.original ?? checkpoint?.portable;
    const view = checkpoint?.view ?? checkpoint?.portable;
    if (!checkpoint || (portable && !original))
      throw fail(
        "compaction_history_unavailable",
        409,
        "Compacted history expired or belongs to another session; restore full history before retrying",
      );
    const nativeCompatible =
      checkpoint.provider === target.provider &&
      (target.provider === "chatgpt-subscription" ||
        checkpoint.targetId === target.id ||
        target.compression?.compatibility?.targets?.includes(
          checkpoint.targetId,
        ));
    if (!portable && !checkpoint.virtual && nativeCompatible) {
      expanded.push(item);
      continue;
    }
    // Codex retains user/system/developer messages before its compaction item. The
    // exact checkpoint already includes these; reinjected, changed instructions stay.
    const replacement = portable
      ? original
      : checkpoint.virtual && checkpoint.targetId === target.id
        ? view
        : original;
    if (!replacement)
      throw fail("compaction_history_unavailable", 409, "Compacted history has no portable source; restore full history before switching providers");
    // Remove only the exact positional prefix already captured by the
    // checkpoint. Content-based set subtraction loses legitimate repeated
    // messages and tool results.
    let covered = 0;
    while (
      covered < expanded.length &&
      covered < original.length &&
      fingerprint(expanded[covered]) === fingerprint(original[covered])
    ) covered++;
    expanded = [...replacement, ...expanded.slice(covered)];
    source = {
      id: checkpoint.targetId,
      provider: checkpoint.provider,
      model: checkpoint.model,
    };
    count++;
  }
  return { input: expanded, count, source };
}

export function portableItems(input) {
  return input.flatMap((item) => {
    // Responses Lite carries current tool declarations as an input item. These
    // are regenerated by Codex for the selected model, not conversation history.
    if (["compaction_trigger", "additional_tools"].includes(item.type))
      return [];
    if (isCompaction(item)) throw fail("compaction_history_unavailable", 409);
    if (item.type === "reasoning") {
      const text = (item.summary ?? []).map((x) => x.text ?? "").join("\n");
      if (!text && item.encrypted_content)
        return [
          {
            type: "message",
            role: "assistant",
            content: [
              {
                type: "output_text",
                text: "[Provider-private reasoning state was not portable; visible messages and tool results are preserved.]",
              },
            ],
          },
        ];
      return text
        ? [
            {
              type: "message",
              role: "assistant",
              content: [{ type: "output_text", text }],
            },
          ]
        : [];
  }
    if (item.type === "message" || item.role) {
      const content =
        typeof item.content === "string"
          ? [
              {
                type: item.role === "assistant" ? "output_text" : "input_text",
                text: item.content,
              },
            ]
          : item.content;
      if (
        !Array.isArray(content) ||
        content.some(
          (x) =>
            !["input_text", "output_text", "input_image", "image_url"].includes(
              x.type,
            ),
        )
      )
        throw fail(
          "history_incompatible",
          400,
          "Only text history can migrate between providers",
        );
      return [
        {
          type: "message",
          role: item.role,
          content: content.map((x) =>
            Object.fromEntries(
              ["type", "text", "image_url", "file_id", "detail"]
                .filter((key) => x[key] !== undefined)
                .map((key) => [key, x[key]]),
            ),
          ),
        },
      ];
    }
    if (
      [
        "function_call",
        "function_call_output",
        "custom_tool_call",
        "custom_tool_call_output",
      ].includes(item.type)
    ) {
      // call_id is the portable association. Provider-generated item ids have
      // incompatible prefixes and must not be replayed to another provider.
      const allowed = [
        "type",
        "call_id",
        "name",
        "arguments",
        "input",
        "output",
        "status",
      ];
      return [
        Object.fromEntries(
          allowed.filter((k) => item[k] !== undefined).map((k) => [k, item[k]]),
        ),
      ];
    }
    throw fail(
      "history_incompatible",
      400,
      "This provider-specific history item cannot migrate safely",
    );
  });
}

export function hasPendingTools(input) {
  const outputs = new Set(
    input
      .filter((x) =>
        ["function_call_output", "custom_tool_call_output"].includes(x.type),
      )
      .map((x) => x.call_id),
  );
  return input.some(
    (x) =>
      ["function_call", "custom_tool_call"].includes(x.type) &&
      !outputs.has(x.call_id),
  );
}
